//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace mypgModel
{
    #region Контексты
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    public partial class mypgEntities : ObjectContext
    {
        #region Конструкторы
    
        /// <summary>
        /// Инициализирует новый объект mypgEntities, используя строку соединения из раздела "mypgEntities" файла конфигурации приложения.
        /// </summary>
        public mypgEntities() : base("name=mypgEntities", "mypgEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта mypgEntities.
        /// </summary>
        public mypgEntities(string connectionString) : base(connectionString, "mypgEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта mypgEntities.
        /// </summary>
        public mypgEntities(EntityConnection connection) : base(connection, "mypgEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Разделяемые методы
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Свойства ObjectSet
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<Mystrings> Mystrings
        {
            get
            {
                if ((_Mystrings == null))
                {
                    _Mystrings = base.CreateObjectSet<Mystrings>("Mystrings");
                }
                return _Mystrings;
            }
        }
        private ObjectSet<Mystrings> _Mystrings;

        #endregion
        #region Методы AddTo
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet Mystrings. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToMystrings(Mystrings mystrings)
        {
            base.AddObject("Mystrings", mystrings);
        }

        #endregion
    }
    

    #endregion
    
    #region Сущности
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mypgModel", Name="Mystrings")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Mystrings : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта Mystrings.
        /// </summary>
        /// <param name="imystr">Исходное значение свойства Imystr.</param>
        public static Mystrings CreateMystrings(global::System.Int32 imystr)
        {
            Mystrings mystrings = new Mystrings();
            mystrings.Imystr = imystr;
            return mystrings;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Imystr
        {
            get
            {
                return _Imystr;
            }
            set
            {
                if (_Imystr != value)
                {
                    OnImystrChanging(value);
                    ReportPropertyChanging("Imystr");
                    _Imystr = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Imystr");
                    OnImystrChanged();
                }
            }
        }
        private global::System.Int32 _Imystr;
        partial void OnImystrChanging(global::System.Int32 value);
        partial void OnImystrChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mystr
        {
            get
            {
                return _Mystr;
            }
            set
            {
                OnMystrChanging(value);
                ReportPropertyChanging("Mystr");
                _Mystr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mystr");
                OnMystrChanged();
            }
        }
        private global::System.String _Mystr;
        partial void OnMystrChanging(global::System.String value);
        partial void OnMystrChanged();

        #endregion
    
    }

    #endregion
    
}
